### ISSUE TITLE
480p fix

### ISSUE THREAD

**Issue by pyorot** [pyorot/wii-swiss-booter#1]
i am also considering how to include this [480p fix mod](https://github.com/RibShark/Wii-Swiss-Booter-480pFix) but i cannot tell the difference well enuff to test the 480p fix out. v1.0 will fix it by virtue of initialising video with new libogc, but the modder said this [doesn't always work](https://github.com/RibShark/Wii-Swiss-Booter-480pFix/releases/tag/v0.3-480p3). but i really don't wanna include an extra i2c module to set a register like the modder did, so if it is actually needed, libogc should expose `__VISetOverSampling`.

**Comment by RibShark** [comment]
The 480p fix only works on RVL-CPU-01 motherboards, and not even all of them, so if you can't see a difference that will be why. The easiest way to tell is to load up the GameCube version of 240p test suite, set the resolution to 480p and look at the checkerboard pattern; the difference should be night and day. According to Extrems a while back, initializing video with the new libogc *should* work but "You need to configure to either a VI_EURGB60 or VI_PAL mode." for it to work in PAL modes; not tested this myself.

**Comment by pyorot** [comment]
thanks for the explanations. i dusted off an old wii to look into this and ended up reproducing issue #4 instead haha. i think, but can't confirm cos i couldn't reproduce it again, that that old (01 motherboard revision) wii still showed a good checkerboard pattern on gamecube 240p test suite, matching what i saw on my newer (60 motherboard revision) wii. i presume that's cos the 240p test suite was compiled after the fix was introduced to libogc in late 2020. so it seems like i can't use it to test wii swiss loader

as such, i can understand porting the fix to wii swiss loader, via a `VIDEO_Init()` call with fixed libogc, but i still don't understand how it's possible for this to only selectively apply to some gamecube games, especially since recent versions of swiss should set the correct register before loading a game. could you explain how you deduced that "The previous fix didn't always work", as mentioned in your [final release](https://github.com/RibShark/Wii-Swiss-Booter-480pFix/releases/tag/v0.3-480p3)?

the current code in this repo does this during init:
```c
VIDEO_Init();
_vMode = VIDEO_GetPreferredMode(NULL);
VIDEO_Configure(_vMode);
```

so i think we're in the clear for the fix working in the general case (on a non-modded video config in all regions). i just opened this issue in case there was any catch i was missing (r.e. your comment on your final release)

**Comment by RibShark** [comment]
GameCube compiled .dol files should not have the 480p fix as that is a Wii exclusive thing, in general it will keep the fix if it was applied by the loader; if you are using a recent HBC build or USB Loader GX that would explain why the checkerboard looks fine.

I can't actually remember why I thought "the previous fix didn't always work", I must have tried it on some (PAL) game or some video mode and it failed, can't remember which though.

**Comment by pyorot** [comment]
> GameCube compiled .dol files should not have the 480p fix as that is a Wii exclusive thing, in general it will keep the fix if it was applied by the loader; if you are using a recent HBC build or USB Loader GX that would explain why the checkerboard looks fine.
> 
> I can't actually remember why I thought "the previous fix didn't always work", I must have tried it on some (PAL) game or some video mode and it failed, can't remember which though.

ah i see, that makes all the sense in my head now lmao. the entrypoint into gamecube mode has to have the register set. i’ve mostly been using 2012 HBC with a hardware rev 60 wii, so not had many chances to test. so doing a VIDEO_Init seems like a good move, and the rest is an obscure hypothesis lost to time. if you can replicate again, do report it :)

cheers for your help with this project, looks like things are getting sorted

**Comment by pyorot** [comment]
i still don’t fully understand what’s been said here so i will leave this here in case i made an oversight and pray that `VIDEO_Configure(VIDEO_GetPreferredMode(NULL))` is correct.

![IMG_3543](https://github.com/user-attachments/assets/48ea4099-40c9-4470-a610-b890af26bb55)
