### ISSUE TITLE
Often fails to load

### ISSUE THREAD

**Issue by RibShark** [pyorot/wii-swiss-booter#4]
This isn't a new problem, but rather one I was hoping would be solved by now. Pretty regularly, the Swiss booter loads up like normal, no errors or anything, but simply loads to a black screen once entering booting MIOS. There is no disc drive noise unlike when it loads properly, so this isn't a video output issue. This happens loading Swiss.dol both from the Wii SD and an SD Gecko too (on different SD cards), so it's likely not a bad SD/reader either. Only way to fix it is to keep rebooting and trying again which is tedious.

It seems to happen more when Swiss has already been loaded before without a power-down.

**Comment by pyorot** [comment]
[this is the one thing we didn’t want to happen](https://youtu.be/_U-7L1tmBAo)

:P

yeah this is the kind of thing that inspired me to rewrite the booter with print output. i haven’t had a single instance of swiss failing to boot myself, but a few of it failing to return to HBC, which is probably a problem with priiloader

what output do you get if you hold A to run tests before letting it boot? screenshot would be good. is it completely OK and then black screen? i only get OK-into-black-screen if i purposely corrupt swiss.dol to crash it

thanks for trying it out ^ - ^ i’ll get back to the 480p issue today as well cos i have some questions to ask

**Comment by RibShark** [comment]
Yeah it's completely OK, and then black screen, all tests show as good so I'm not sure what the problem is; like I say it happens more often if I boot into Swiss, then hit the power button on the Wii to reset back to Wii mode and then try to boot into Swiss again.

**Comment by RibShark** [comment]
I did a clean install today on a fresh NAND using Ohneschwanzenegger; definitely not installed anything that overwrites BC. I'm using the latest build of Swiss so that's not the problem either... definitely confused why it's happening to me and not you.

**Comment by pyorot** [comment]
i tested r1742 on usb and had 5 successful boot and exits in a row. i’ve noticed devices cause software to crash if hardware is bad often (especially in priiloader), like a stuttering disc drive or chipped sd card that doesn’t fully plug in, so it’s good to remove as many devices as poss (and the disc) to test, but that’s just a vague suggestion

in the code here, i feel like there might be a variable that needs to be memory-aligned but isn’t, so i’ll have a read in a sec to check. we have to make sure this app leaves the registers clean for the next one, but idk what else i need to do to ensure that. i can ask around

but if somewhere BC-onwards there’s an error then idk how to catch that in the loader. sucks that the symptom isn’t even reproducible on my end

 i’ll post again here if i have any more ideas

**Comment by pyorot** [comment]
further work for this app (may add a new issue later):
- verify BC
- make some other custom homebrew to test out GameCube mode booting

actually yeah, have you tried a different gc homebrew app with the loader? gcmm say. you’d just need to rename it to swiss.dol haha

**Comment by pyorot** [comment]
i went thru and memory-aligned anything that could do with it (meaning the filepath buffer for where it looks for swiss and a buffer that stores a pointer that's read in from swiss.dol). small chance this helps but you never know. again, this is actually a .7z file whose extension i changed to get GitHub to accept it

[wii-swiss-booter.txt](https://github.com/user-attachments/files/17894474/wii-swiss-booter.txt)

**Comment by pyorot** [comment]
i actually reproduced this lol... on my other wii

i tested:
- wii swiss booter v0.3 (W)
- [ribshark video fix 2](https://github.com/RibShark/Wii-Swiss-Booter-480pFix/releases/tag/v0.3-480p3) (R)
- the test commit of mine i sent in the last message (S)

all tested on:
- Swiss r1742
- 240p test suite i downloaded today

**results**: never a problem booting any of these on my newer black wii. white wii... i believe i got into the 240p test suite once after first power on, and then not a single time after that, despite even unplugging and restarting it 🤦‍♂️

- Swiss r1742: locked up on black screen (W, R, S); had to be shutdown with power button hold (W) / rebooted on power button press (R, S)
- 240p suite: rebooted automatically (W, R, S)

seems like a problem in the cMIOS that affects older hardware, combined with buggy error handling in some of the payload homebrew? worth noting as well is i couldn't get HBC to recognise an sd card in the wii slot no matter what i did, so maybe it's affected by instability caused by failed device mounting

if you could confirm that you tested with no extraneous devices attached and with this patched version i posted above, then i'll leave this issue open for future investigators to look at

**Comment by pyorot** [comment]
testing is ongoing and i have a lead on a possible regression in swiss itself (on older wiis). the same problem happening in 240p test suite indicates it may be a problem in libogc(2)

swiss r1060: booted 4/5 times
swiss r1420: booted 4/5 times
swiss r1592: booted 0/5 times
swiss r1742: booted 0/5 times

updates to be edited into this post

**Comment by pyorot** [comment]
@Extrems could i please get hold of a recent swiss release in uncompressed .dol format?

**Comment by Extrems** [comment]
You can take the debug `.elf` and use `elf2dol` on it manually.

**Comment by pyorot** [comment]
now that the source code for the cMIOS is [back online](https://github.com/ForwarderFactory/cmios-wiigator-installer), i want to note down a summary of where we are with this issue and directions for future work. it's some sort of memory corruption, and i'll post snippets of Extrems's commentary from eir discord:

> I don't want to touch [the cMIOS] though, even though there are annoyances with what it does. Like it clobbers a magic value that MIOS writes. And partially overwrite its own magic before handing us control.

> Okay, a restart means the LZMA2 stream is corrupted. [An uncompressed dol] won't work around the memory corruption. It just might give you a chance of getting something maybe partially working. Hence the nonsensical crash dumps. The CRC is a good thing as it makes sure the data is correct. You don't have a CRC with the uncompressed executable.

> It's possible this is a stop 'n' swop kind of situation, and the only way to address it would be to burn Swiss or gekkoboot into MIOS. (you think some RAM gets cleared or re-initialised during the reboot?) Or it's just not powered.

(as an aside, cMIOS ft gekkoboot would be hype... tho not an ideal solution to require everyone to buy an sd gecko for guaranteed compatibility when the old setup seems to work in 90% of situations)

Extrems has made a new gamecube homebrew loading setup as part of a wii swiss booter release with swiss baked into it, in swiss commits [r1761](https://github.com/emukidid/swiss-gc/commit/3c189069031045d6787053e9a9ae9e76a0b3a813), [r1762](https://github.com/emukidid/swiss-gc/commit/4b6f74da5ebe6e40c365e65b46270ceff9775688) and [r1763](https://github.com/emukidid/swiss-gc/commit/2b7c57b7305f1795c57eea61fafb4aed0e6b2456). it's quite a different paradigm from the old setup, but a good place to start on reinventing the wii swiss booter side of the setup. it still uses the old cMIOS, which is probably the thing we should focus experimentation on

if i wanted to further work on this issue, i would want to clear up the following preliminary inconveniences:

1. there's no wad installation library (one separate from the many, many apps that copy and paste code from patchmii or wad manager). probably start by repackaging [this code](https://github.com/Naim2000/csm-installer/blob/wad-installer/source/wad.c) and publishing to [systemwii](https://github.com/systemwii) or elsewhere

2. the installer in the cMIOS repository is outdated and inefficient, and needs to be whittled down into the MIOS patching code

3. #1 and #2 could be built into a fork of this repo that lets us then rapidly install a test cMIOS and try to use the gamecube dol executor code to boot swiss with it

4. the gamecube dol executor is kinda cobbled-together as well (the setup runs the DolLoader binary twice, both in wii swiss booter and in the cMIOS, for reasons I can't explain...); need to carefully document and understand exactly what's going on, then try to reimplement Extrems's new setup

with all that said, i will refer this to dolphin's devs to have a look at. and i can't help but think we could work around the problem to everyone's satisfaction by just messing around with where in memory all the dols are loaded

**Comment by pyorot** [comment]
once Swiss does a release with the wii booter included, more data is welcome from people trying out both that and this repo's v1.0 release, with compressed (i.e. normal) and uncompressed swiss.dol, the latter if you have dol2elf to hand. currently it seems like it's just my old white wii that ain't havin any of this and goes 0% success rate when booting compressed swiss r17xx

**Comment by pyorot** [comment]
aite erry1, thanks for your patience. i have the bug diagnosed and a proposed future solution! it's a decent bit of work tho so idk who or when it will be done

[**full write-up**](https://github.com/pyorot/debug-cmios)

**short-term solution** @RibShark you may consider cloning the repo i just linked (remember to recurse submodules), dropping in a swiss.dol, and just compiling a new cMIOS with swiss built-in, then booting Swiss by compiling the included `test.c` or [this branch](https://github.com/pyorot/wii-swiss-booter/tree/cmios-experiment) of this repo. you can remove any debugging `sleep`/`printf` calls you want. idk if this should be distributed cos it's a kind of incomplete solution and having weird cMIOSes proliferate is annoying for integrity-testing the Wii, but if nothing else comes of this project soon then it could be good for speedrunners.

**long-term solution** tl;dr: the cMIOS installer will let you assign .dol files for GameCube homebrew apps from SD/USB to buttons, will generate and install a cMIOS with those built-in, and we'll add a patch to Priiloader that just boots the cMIOS, then you hold buttons to get into your chosen app. one day, Priiloade will hopefully also have button-combo boot, and we can whittle Swiss down into an auto-booter, to get the Wii to just boot the disc in 480p from startup :)).

**Comment by RibShark** [comment]
> **short-term solution** @RibShark you may consider cloning the repo i just linked (remember to recurse submodules), dropping in a swiss.dol, and just compiling a new cMIOS with Swiss built-in

doesn't seem like there are any build rules for transforming swiss.dol into swiss_dol.h, so the build fails for me (I used --recursive on clone so that isn't the issue).

**Comment by pyorot** [comment]
> > **short-term solution** @RibShark you may consider cloning the repo i just linked (remember to recurse submodules), dropping in a swiss.dol, and just compiling a new cMIOS with Swiss built-in
> 
> doesn't seem like there are any build rules for transforming swiss.dol into swiss_dol.h, so the build fails for me (I used --recursive on clone so that isn't the issue).

the only thing i can think of is that swiss.dol may be in the wrong folder; should be in `lib/cmios/data`, which i realise doesn't exist in the repo cos i didn't put anything in it 😬

the relevant rule is this in `recipes.mk`
```makefile
# injected binary data (using the bin2s tool)
$(CACHE)/data/%.o : % | $(CACHE)/data
	$(SILENTMSG) [b → o] $< → $@
	$(eval _tmpasm := $(shell mktemp))
	$(SILENTCMD)bin2s -a 32 -H `(echo $@ | tr . _ | sed "s/_o$$//")`.h $< > $(_tmpasm)
	$(SILENTCMD)$(CC) -c -x assembler-with-cpp $(CPPFLAGS) $(ASFLAGS) $(_tmpasm) -o $@
	@rm $(_tmpasm)
```

the Makefile in `lib/cmios` triggers it with
```makefile
BINS		 =	data
BINEXTS		 =	.dol
```

and the intermediate step is (output.mk):
```makefile
VPATH := $(SRCS) $(BINS) # built-in variable specifying search locations for prerequisites
# files are found by dir/*.*, then filtered by a list of extensions ("%" must be prepended to each extension)
BINFILES := $(foreach dir, $(BINS), $(filter $(foreach ext, $(BINEXTS), %$(ext)), $(wildcard $(dir)/*.*)))
BINOFILES:= $(foreach file, $(BINFILES), $(CACHE)/data/$(notdir $(file).o))
```

**Comment by pyorot** [comment]
in the end, this was annoying me so i [compiled swiss r1788 into a cmios](https://github.com/pyorot/debug-cmios/releases/tag/swiss-cmios-r1788) and that can be used to resolve this issue, hopefully. it can be loaded cleanly using the [latest release of wii swiss booter](https://github.com/pyorot/wii-swiss-booter/releases/tag/v1.1). it's an interim solution, and further progress on the underlying problem can be tracked at the [debug cmios repo](https://github.com/pyorot/debug-cmios)
